# Generated by Django 3.0.6 on 2020-05-05 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net_automation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='ssh_port',
            field=models.IntegerField(default=22),
        ),
        migrations.AlterField(
            model_name='device',
            name='vendor',
            field=models.CharField(choices=[('mikrotik', 'Mikrotik'), ('cisco', 'Cisco')], max_length=255),
        ),
    ]
